package com.espto.espto.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum EsporteTipo {

    VOLEI_CADEIRA_RODAS(TypeDisability.DEFICIENCIA_FISICA),
    BASQUETE_CADEIRA_RODAS(TypeDisability.DEFICIENCIA_FISICA),
    NATACAO_ADAPTADA(TypeDisability.DEFICIENCIA_FISICA),
    ATLETISMO_ADAPTADO(TypeDisability.DEFICIENCIA_FISICA),
    TENIS_CADEIRA_RODAS(TypeDisability.DEFICIENCIA_FISICA),

    FUTEBOL_CEGOS(TypeDisability.DEFICIENCIA_VISUAL),
    GOALBALL(TypeDisability.DEFICIENCIA_VISUAL),
    JUDO(TypeDisability.DEFICIENCIA_VISUAL),

    BASQUETE_PARALIMPICO(TypeDisability.DEFICIENCIA_INTELECTUAL),
    ATLETISMO_PARALIMPICO_INTELECTUAL(TypeDisability.DEFICIENCIA_INTELECTUAL),
    NATACAO_PARALIMPICA_INTELECTUAL(TypeDisability.DEFICIENCIA_INTELECTUAL),

    FUTEBOL_SILENCIOSO(TypeDisability.DEFICIENCIA_AUDITIVA),
    VOLEI_SILENCIOSO(TypeDisability.DEFICIENCIA_AUDITIVA),
    BASQUETE_SILENCIOSO(TypeDisability.DEFICIENCIA_AUDITIVA),

    OUTRO_DEFICIENCIA_INTELECTUAL(TypeDisability.DEFICIENCIA_INTELECTUAL),
    OUTRO_DEFICIENCIA_VISUAL(TypeDisability.DEFICIENCIA_VISUAL),
    OUTRO_DEFICIENCIA_FISICA(TypeDisability.DEFICIENCIA_FISICA),
    OUTRO_DEFICIENCIA_AUDITIVA(TypeDisability.DEFICIENCIA_AUDITIVA);


    private final TypeDisability typeDisability;

}
